version: '3'

services:
  api:
    container_name: api
    restart: always
    expose:
      - 6556
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db-api
    networks:
      - default-api

  db-api:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: nellcorp-desafio-api-db
    networks:
      - default-api

networks:
  default-api:
