version: '3'

services:
  db-api:
    image: bitnami/postgresql
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRESQL_USERNAME: root
      POSTGRESQL_PASSWORD: root
      POSTGRESQL_DATABASE: nellcorp-desafio-api-db
    networks:
      - default-api

  api:
    container_name: api
    restart: always
    environment:
      PORT: 6556
      DATABASE_URL: "postgresql://root:root@db-api:5432/nellcorp-desafio-api-db?schema=public"
    ports:
      - 6556:6556
    build:
      context: ./
      dockerfile: Dockerfile
    depends_on:
      - db-api
    networks:
      - default-api

networks:
  default-api:
